---
format: html
title: "GSB 544 Midterm"
author: "Ryan Perez"
code fold: false
self-contained: true
---

In [32]:
import pandas as pd
import plotnine as p9

# If you want to use the raw string approach, use 'r' before the string.
midterm = pd.read_csv(r"C:\Users\ryanc\Desktop\GSB_519\national_park_trails.csv")

midterm

,trail_id,name,area_name,city_name,state_name,country_name,_geoloc,popularity,length,elevation_gain,difficulty_rating,route_type,visitor_usage,avg_rating,num_reviews,features,activities,units
0,10020048,Harding Ice Field Trail,Kenai Fjords National Park,Seward,Alaska,United States,"{'lat': 60.18852, 'lng': -149.63156}",24.8931,15610.598,1161.8976,5,out and back,3.0,5.0,423,"['dogs-no', 'forest', 'river', 'views', 'water...","['birding', 'camping', 'hiking', 'nature-trips...",i
1,10236086,Mount Healy Overlook Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73049, 'lng': -148.91968}",18.0311,6920.162,507.7968,3,out and back,1.0,4.5,260,"['dogs-no', 'forest', 'views', 'wild-flowers',...","['birding', 'camping', 'hiking', 'nature-trips...",i
2,10267857,Exit Glacier Trail,Kenai Fjords National Park,Seward,Alaska,United States,"{'lat': 60.18879, 'lng': -149.631}",17.7821,2896.812,81.9912,1,out and back,3.0,4.5,224,"['dogs-no', 'partially-paved', 'views', 'wildl...","['hiking', 'walking']",i
3,10236076,Horseshoe Lake Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73661, 'lng': -148.915}",16.2674,3379.614,119.7864,1,loop,2.0,4.5,237,"['dogs-no', 'forest', 'lake', 'kids', 'views',...","['birding', 'hiking', 'nature-trips', 'trail-r...",i
4,10236082,Triple Lakes Trail,Denali National Park,Denali National Park,Alaska,United States,"{'lat': 63.73319, 'lng': -148.89682}",12.5935,29772.790,1124.7120,5,out and back,1.0,4.5,110,"['dogs-no', 'lake', 'views', 'wild-flowers', '...","['birding', 'fishing', 'hiking', 'nature-trips...",i
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3308,10008302,Silversword Loop Via Halemau'u Trail,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.75275, 'lng': -156.22884}",9.3861,20116.750,1105.8144,5,loop,2.0,4.5,43,"['dogs-no', 'views', 'wild-flowers']","['birding', 'hiking', 'nature-trips']",m
3309,10236001,Keonehe'ehe'e Trail,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.714480000000002, 'lng': -156.25072}",9.1555,28324.384,1171.9560,5,out and back,2.0,5.0,22,"['dogs-no', 'views', 'wildlife']","['backpacking', 'camping', 'hiking']",m
3310,10258707,Red Hill Overlook Summit Trail,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.71007, 'lng': -156.25357}",8.5066,321.868,3.9624,1,out and back,NaN,4.5,31,"['dogs-no', 'kids', 'views']","['hiking', 'walking']",m
3311,10014989,Kaupo Trail,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.64981, 'lng': -156.137}",8.3240,19312.080,1670.9136,5,out and back,1.0,4.0,8,"['dogs-no', 'views', 'wildlife']",['hiking'],m
3312,10259465,Ka Lu'u o ka O'o Cinder Cone via Crater and Sl...,Haleakala National Park,Kula,Maui,Hawaii,"{'lat': 20.71449, 'lng': -156.25085}",2.4176,8368.568,510.8448,3,loop,2.0,4.5,45,['views'],['hiking'],m

# Question 1.1

In [36]:
ca_parks = midterm[(midterm['state_name'] == 'California')].copy()

ca_parks.head() #707 trails from 3313

,trail_id,name,area_name,city_name,state_name,country_name,_geoloc,popularity,length,elevation_gain,difficulty_rating,route_type,visitor_usage,avg_rating,num_reviews,features,activities,units
219,10026910,Vernal and Nevada Falls via the Mist Trail,Yosemite National Park,Yosemite Valley,California,United States,"{'lat': 37.73495, 'lng': -119.56619}",68.1488,10299.776,667.8168,3,loop,3.0,5.0,1869,"['dogs-no', 'forest', 'partially-paved', 'rive...","['birding', 'hiking', 'nature-trips', 'walking']",i
220,10005895,Upper Yosemite Falls Trail,Yosemite National Park,Yosemite Valley,California,United States,"{'lat': 37.74237, 'lng': -119.60223}",53.6280,11587.248,967.7400,7,out and back,3.0,5.0,1351,"['dogs-no', 'forest', 'river', 'views', 'water...","['birding', 'hiking', 'nature-trips', 'trail-r...",i
221,10005585,Half Dome Trail,Yosemite National Park,Yosemite Valley,California,United States,"{'lat': 37.73465, 'lng': -119.56583}",52.5316,23818.232,1573.9872,7,out and back,3.0,5.0,1196,"['dogs-no', 'forest', 'partially-paved', 'rive...","['hiking', 'nature-trips', 'rock-climbing']",i
222,10026952,Moro Rock Trail,Sequoia National Park,Three Rivers,California,United States,"{'lat': 36.54685, 'lng': -118.76565}",44.1235,643.736,56.9976,3,out and back,3.0,4.5,701,"['dogs-no', 'river', 'views', 'waterfall', 'wi...","['birding', 'hiking', 'nature-trips', 'rock-cl...",i
223,10011926,Lower Yosemite Falls Trail,Yosemite National Park,Yosemite Valley,California,United States,"{'lat': 37.74587, 'lng': -119.59266}",43.3499,1609.340,15.8496,1,loop,3.0,4.5,925,"['ada', 'dogs-leash', 'forest', 'kids', 'parti...","['birding', 'hiking', 'nature-trips', 'trail-r...",i

In [37]:
ca_parks['length_miles']=ca_parks['length'].apply(lambda x : x*0.000621371)

In [38]:
top_4_trails = ca_parks.sort_values(by='length', ascending=False).head(4)

top_4_trails.reset_index(inplace = True)
top_4_trails.head()

,index,trail_id,name,area_name,city_name,state_name,country_name,_geoloc,popularity,length,elevation_gain,difficulty_rating,route_type,visitor_usage,avg_rating,num_reviews,features,activities,units,length_miles
0,912,10501331,John Muir Trail,Yosemite National Park,Lone Pine,California,United States,"{'lat': 36.58686, 'lng': -118.24013}",0.9673,339570.740,13165.8360,3,point to point,NaN,0.0,0,"['forest', 'lake', 'views', 'wild-flowers', 'w...","['backpacking', 'birding', 'camping', 'hiking'...",i,210.999410
1,251,10004781,John Muir Trail via Yosemite Valley,Yosemite National Park,Yosemite Valley,California,United States,"{'lat': 37.73476, 'lng': -119.56629}",24.0723,326856.954,14029.9440,5,point to point,3.0,4.5,129,"['dogs-no', 'forest', 'lake', 'river', 'views'...","['backpacking', 'camping', 'hiking']",i,203.099432
2,727,10270059,Ridgecrest to Death Valley OHV Trail,Death Valley National Park,Ridgecrest,California,United States,"{'lat': 35.61407, 'lng': -117.67073}",3.6185,266989.506,3045.8664,3,point to point,2.0,4.5,4,"['dogs-no', 'historic-site', 'views', 'wild-fl...","['nature-trips', 'off-road-driving']",i,165.899536
3,835,10418330,Big SEKI Loop,Kings Canyon National Park,Hume,California,United States,"{'lat': 36.79608, 'lng': -118.58322}",2.1531,233676.168,10944.7584,7,loop,1.0,5.0,2,"['forest', 'views', 'wildlife']","['backpacking', 'birding', 'camping', 'hiking'...",i,145.199594

# Question 1.2

In [39]:
midterm2 = ca_parks[(ca_parks['elevation_gain'] < 500) & (ca_parks['length'] < 5000) & (ca_parks['difficulty_rating'] < 4)]

midterm2answer = midterm2[["area_name", "avg_rating"]].groupby("area_name").mean()

max_row = midterm2answer.loc[midterm2answer["avg_rating"].idxmax()]

max_row

avg_rating    4.444444
Name: Kings Canyon National Park, dtype: float64

# Question 1.3

In [30]:
midterm3 = midterm[midterm['area_name'].str.contains('land')] 

q3 = midterm3['area_name'].unique()
q3

array(['Channel Islands National Park', 'Badlands National Park',
       'Canyonlands National Park'], dtype=object)

# Question 1.4

In [34]:
midterm4 = midterm.copy()
np_trails_new = midterm4[['avg_rating', 'difficulty_rating', 'popularity', 'visitor_usage']].copy()
np_trails_new

      avg_rating  difficulty_rating  popularity  visitor_usage
0            5.0                  5     24.8931            3.0
1            4.5                  3     18.0311            1.0
2            4.5                  1     17.7821            3.0
3            4.5                  1     16.2674            2.0
4            4.5                  5     12.5935            1.0
...          ...                ...         ...            ...
3308         4.5                  5      9.3861            2.0
3309         5.0                  5      9.1555            2.0
3310         4.5                  1      8.5066            NaN
3311         4.0                  5      8.3240            1.0
3312         4.5                  3      2.4176            2.0

[3313 rows x 4 columns]

In [35]:
from plotnine import ggplot, aes, geom_density, facet_wrap, ggtitle

(ggplot(np_trails_new, aes(x="score"))
+ geom_density()
+ facet_wrap('~ measure', scales = 'free') 
+ ggtitle("Overall distribution of various trail scores in National parks")
)

PlotnineError: 'At least one layer must contain all variables used for facetting'

# Question 1.5

In [ ]:
from plotnine import *
from plotnine.scales import *

(ggplot(ca_parks, aes(x="area_name", y="num_reviews", fill = "area_name"))
+ geom_boxplot()
+ scale_y_continuous(breaks=([1, 10, 100, 1000]),
                    labels = [1, 10, 100, 1000],
                    trans = 'log2') 
+ scale_x_continuous(guide=False)
+ labs(
  x = "",
  y = "",
  title = "Number of reviews per trail for CA Parks"
)
+ ggtitle()
+ theme(x=element_text(rotation=45, hjust=1)) 
)

# Question 2.1

In [49]:
def recommend_trails(midterm, area_name, min_elev=None, max_elev=None, min_rating=None, route_type=None):
    
    if min_elev is None:
        min_elev = min(midterm['elevation_gain'] for trail in dataset if trail['area_name'] == area_name)

    recommended_trails = []

    for trail in midterm:
        if midterm['area_name'] == area_name:
            if min_elev is not None and trail['elevation_gain'] < min_elev:
                continue
            if max_elev is not None and trail['elevation_gain'] > max_elev:
                continue
            if min_rating is not None and trail['avg_rating'] < min_rating:
                continue
            if trail_type is not None and trail['route_type'].lower() != trail_type.lower():
                continue
            recommended_trails.append(trail)

    return recommended_trails

In [50]:
recommend_trails(midterm, "Haleakala National Park", min_elev = 1000, min_rating = 4)

ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

# Question 2.2

In [ ]:
def scrape_temps(month = None):
  
  my_url = "https://www.extremeweatherwatch.com/us-state-averages"
  response = requests.get(my_url)
  soup = BeautifulSoup(response.content, "html.parser")
  
    
    
  ## More of your code here
  
  
  return scrape_month_temp

In [ ]:
scrape_month_temp(month = "january")

# Question 2.3

### Part a

In [ ]:
recommend_trails(midterm, max_elev = 3000, min_elev = 1000, min_rating = 4.5)

### Part b

In [ ]:
scrape_month_temp(month = "january")

### Part c

In [ ]:
pd.concat([midterm, tempdata])

### Part d

In [51]:
#Woefully unprepared for this midterm. I hope to make up for it by finishing my labs and learning the material so I can do well on the final.